version: "3.7"

services:
  atm:
    build: 
      context: .
      dockerfile: atm.Dockerfile
    ports:
      - "8080:8080"
    networks: 
      - production-network
    container_name: atm
    depends_on: [database]
  database:
    build: 
      context: ./postgres-docker-config/
      dockerfile: postgres.Dockerfile
    ports: 
      - "5432:5432"
    networks:
      - production-network
    container_name: postgres
    
    
  
networks: 
  production-network:
    driver: bridge